version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/:/docker-entrypoint-initdb.d/
      - db-data:/var/lib/postgresql/data
    # command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
 
volumes:
  db-data:
